### ISSUE TITLE
Windows Server 2016 Installation

### ISSUE THREAD

**Issue by Mululu** [TWC-Software/DaemonMaster#12]
Can not install on Windows Server 2016. No error message

**Comment by MCPC10** [comment]
Hey,
Can you open the installer or not ?
Sorry for my english ;)

**Comment by Mululu** [comment]
No i click on it but nothing happens :/

Whats your main language :)

**Comment by MCPC10** [comment]
Ok lol,
German ;)

**Comment by MCPC10** [comment]
The installer does not come from me (WiX Setup).

**Comment by Mululu** [comment]
Mh ich habe halt nach einer alternative zu FireDaemon gesucht.

**Comment by MCPC10** [comment]
Jo hab ich mir auch gedacht und haben dann selber angefangen eine zu machen ;)
Aber bin selbst kein Profi und lerne jeden Tag dazu, deshalb sind Fehler bei mir normal.
Aber das der gar nicht startet wundert mich (normal gibt der Fehler oder so).

**Comment by stuffi3000** [comment]
Ich denke Kompatibilitätsmodus hast du schon versucht, oder? ;)

**Comment by stuffi3000** [comment]
Ich denke Kompatibilitätsmodus hast du schon versucht, oder? ;)

**Comment by Mululu** [comment]
Ja schon getestet

**Comment by stuffi3000** [comment]
@MCPC10 Könntest du ihm nicht eine schon installierte Version schicken? Oder ist der Installer so wichtig?

**Comment by MCPC10** [comment]
@stuffi3000  Ja kann ich aber die Version die ich jetzt habe ist noch Dev und hat kram drin der noch gar nicht im repo ist (experimentell).

**Comment by MCPC10** [comment]
@Mululu Werde dir ne portable Version erstellen (ohne installer) hoffe dann geht es, kann aber was dauern (heute bzw morgen, denn ich muss die stable Sachen finden xD).

**Comment by Mululu** [comment]
Ok vielen dank

Etwas Testzeit von FireDaemon habe ich noch

**Comment by MCPC10** [comment]
jo dann ;)

**Comment by MCPC10** [comment]
Du nutzt ja nicht das starten im User context, denn da haben wir derzeit Probleme (Deshalb ist es abgeschaltet)

**Comment by Mululu** [comment]
Nein ganz normal

**Comment by MCPC10** [comment]
[Release_DM_V0.2.3.0.zip](https://github.com/TWC-Software/DaemonMaster/files/1632673/Release_DM_V0.2.3.0.zip)

So hier ist die portable Version (ist ne Version die noch nicht öffentlich ist aber en paar Fehler Behebungen enthält, hoffe die funktioniert bei dir xD). 
Wenn du Probleme findest kannst du sie mir bitte melden, dann kann ich die fixen ;).

**Comment by Mululu** [comment]
Ok dankeschön probiere es gleich mal aus

**Comment by Mululu** [comment]
Soweit funktioniert es.

Kann nur keine Java Anwendungen ausführen.

Unable to acces jarfile spigot.jar

kann vll. an den rechten liegen habe aber das Programm bereits als Administrator ausgeführt.

**Comment by stuffi3000** [comment]
Spigot? Das ist eine Minecraft server Java Datei

**Comment by Mululu** [comment]
Ja genau

**Comment by stuffi3000** [comment]
Ah okay, du hostest den. Dachte schon MCPC10 hätte irgendwas im Code hängen lassen. Vielleicht kannst du die Berechtigungen den .jar Datei ändern damit das Programm Zugriff bekommt

**Comment by MCPC10** [comment]
Du musst die javaw.exe im java ordner auswählen und als Parameter -jar "Pfad zur jar" glaube ich xD

**Comment by MCPC10** [comment]
ohne "" natürlich xD

**Comment by Mululu** [comment]
Ok ich teste mal

**Comment by MCPC10** [comment]
funktioniert es jetzt ? xD

**Comment by Mululu** [comment]
Das Problem liegt auf jedenfall an den Rechten. Dann funktioniert es auch nur mit einer Start.bat 

Am besten wäre es wenn man den Benutzer angeben könnte mit dem der Dienst gestartet werden soll. Wie ja schon vorgesehen aber leider ausgegraut

**Comment by MCPC10** [comment]
Ok, komisch denn der Service läuft unter dem LocalSystem Account (höchste Rechte in Windows). 
Die Funktion ist schon implementiert aber en bisschen verbuggt und man bekommt kein UI0Detect Fenster mehr (aber ich kann sie dir gerne zum testen freischalten ;)).

**Comment by Mululu** [comment]
Das Fenster brauche ich nicht. Ich weiß ja das da was läuft. Wäre nett

**Comment by MCPC10** [comment]
So hab noch en paar Probleme (der nimmt das Passwort nicht an, und das fixen dauert noch -_-). Aber du kannst das bei dir selber probieren einfach in Dienste gehen, dann nach dem DisplayName suchen, Doppelklick draufmachen, auf Anmelden gehen und dein Nutzer und pw eingeben (übernehmen nicht vergessen ;)).

**Comment by MCPC10** [comment]
Geht das denn mit einem anderen Nutzer oder auch nicht ?

**Comment by Mululu** [comment]
Leider nicht ich gebe es vorerst auf. Trotzdem danke

**Comment by MCPC10** [comment]
Vielleicht kommt es jetzt schon zu spät aber wenn es dir hilft, denn es sollte jetzt auch auf Windows Server 2016 laufen.

(Da ich jetzt auch einen Windows Server 2016 zur Verfügung habe konnte ich das Problem hoffentlich  lösen. => Denn bei mir geht es jetzt)
