### ISSUE TITLE
cmdline parameters

### ISSUE THREAD

**Issue by Adanteh** [TWC-Software/DaemonMaster#13]
Is there any chance you could add services through command line? I'm trying to mostly automatize the creation of dedicated game servers, but I'd like to keep the fancy autorestarting and GUI from this, so it would be good if services could be added from a command line call

**Comment by MCPC10** [comment]
Hey,
I can make that but it take some time to do that and which parameters do you need.

**Comment by Adanteh** [comment]
Having the import available would be best, that seems like less work, plus it's easy enough to format those json files. Pretty much a `.\daemonmaster.exe -i "pathtofile.dmdf"` would work wonders I think.

**Comment by MCPC10** [comment]
But how can I tell you, that the install was successful (without GUI).

**Comment by MCPC10** [comment]
When I have finished the first test version, I give it to you, so that you can test it and give me feedback than.

**Comment by Adanteh** [comment]
They're just some python scripts, I use the json package to write the import file (Seeing that's JSON too)

**Comment by MCPC10** [comment]
So I'm working on the cmd line params but it can took some time to do that (because we currently have a lot of work at work xD). But when you are able to compile the code that you can test the current implementation (experimental => lot of bugs).

**Comment by drhax9908** [comment]
This would be a useful feature. Thank you for considering this! And, another thanks for (unrelated to this issue) creating this software to begin with, as it's a free alternative to Core Technologies AlwaysUp, something I MIGHT have paid for, were it not 50 USD (I'm Canadian, so this is an exchange rate related complication, not a hatred for paid software. I may have actually bought it had it not cost that much, and had I not found this instead). Thanks to DaemonMaster, I can run a VMWare Virtual Machine as a Windows Service.

**Comment by drhax9908** [comment]
Wow, I just saw the date this issue was made. Apologies for what forums call a "Necro-bump"

**Comment by MCPC10** [comment]
Np and thanks xD
So the problem for me now is that I don't have the time (due to a lot of work) to make the cmd line finish (dev version is out - source only) but I hope that I can make it in the next months.

**Comment by MCPC10** [comment]
So in the last release the cmdline interface hopefully should work. It would be nice, if anyone has more time to test that, then me. xD.
