### ISSUE TITLE
Screenshots please

### ISSUE THREAD

**Issue by gerroon** [TWC-Software/DaemonMaster#14]
It is always helpful to know what we are getting.

thanks

**Comment by MCPC10** [comment]
Sorry for my late answer.
At the moment we have a lot of stress at work, so I doesn't have the time to do it directly but I will make as fast as possible. ;)

Mike Cr

**Comment by MCPC10** [comment]
So here are the screenshots xD. 
(I put it also later in the readme.md file.)

![dm1](https://user-images.githubusercontent.com/8211507/50426834-40662d00-0898-11e9-9c39-4895a96f3885.PNG)
![dm_edit](https://user-images.githubusercontent.com/8211507/50426835-40662d00-0898-11e9-8085-f6f72bb4e175.PNG)
![dm_edit2](https://user-images.githubusercontent.com/8211507/50426836-40662d00-0898-11e9-96f2-659fa1b30c3e.PNG)
![dm_edit1](https://user-images.githubusercontent.com/8211507/50426837-40662d00-0898-11e9-8f7c-f6bba54dfaad.PNG)
