### ISSUE TITLE
French - Suggestion for translation

### ISSUE THREAD

**Issue by daerlnaxe** [TWC-Software/DaemonMaster#27]
Hi,

Good job for your application ,i hope you will continue it !!!.

1) When I want to select the folder of the targeted application, I get the following message
"
Recherche des tags du fichier
"
![image](https://github.com/user-attachments/assets/e29e4faa-8ffb-4798-bb8f-4461e149d984)

IDK if you mean something about tags or if there is a translation problem (i'm very bad to write in english).

For me, that discover your (fabulous) application, it's something like "browse folders" even more, something like "find the folder of the application targeted" => "Recherche du dossier de l'application ciblée"

2)For "nom service" => "nom du service"

----
In French/Français

![image](https://github.com/user-attachments/assets/bea44691-e3b5-4afe-8397-851f70c925b8)

"Enclencher le service" must be "Démarrer le service"

"Kill Service"  for me it's perfect even if it's not french it's explicit, but if you want to change it, this is the french windows version you get in the task manager (program part, there is nothing in "services") => "Fin de tâche" then maybe "Fin du service" but it's less explicit than "kill"
![image](https://github.com/user-attachments/assets/41e1718c-439e-4132-9aa6-ca035a603e25)

----
I hope it's useful

**Comment by MCPC10** [comment]
Hi, 
Of course it's useful :). Any help is welcome.
I will implement your suggestions in the next version.

**Comment by MCPC10** [comment]
I see that most, if not all, of your suggestions have already been implement by @stuffi3000 with the commit  9042e682ed20718a133d72dc4984363c05098402
Which means that I should publish a new version xDDD

**Comment by daerlnaxe** [comment]
Cool, good new !
